GET http://localhost:3001/cards

###

GET http://localhost:3001/cards/11

###

GET http://localhost:3001/cards/613c70e3171f8f2ca01a6eaf


#************************ New Card ************************
###
POST http://localhost:3001/cards
content-type: application/json

{
  "front": [
    {
      "id": "12-0938412-905",
      "type": "TEXT",
      "htmlContent": "<p>What is the solution to the quadratic Equation?</p>"
    },
    {
      "id": "-0934239841-27349791348",
      "type": "MATH",
      "latex": "ax^2+bx+c=0"
    }
  ],
  "back": [
    {
      "id": "0949485858493",
      "type": "MATH",
      "latex": "x=\\frac{-b\\pm\\sqrt{b^2-4ac}}{2a}"
    }
  ],
  "difficultyLevels": {
    "veryEasy": false,
    "easy": false,
    "medium": false,
    "hard": true,
    "veryHard": false
  },
  "tags": [
    "Abstract Algebra"
  ]
}


###

POST http://localhost:3001/cards
content-type: application/json

{
  "front": [
    {
      "id": "d02lqa-3l21kjfds",
      "type": "TEXT",
      "htmlContent": "Solve this DE"
    },
    {
      "id": "04390234-9085775747311",
      "type": "MATH",
      "latex": "\\frac{d^2y}{dt} = -\\omega^2 y"
    }
  ],
  "back": [
    {
      "id": "al;qwlelasdfl;kj",
      "type": "MATH",
      "latex": "y = C_1 \\cos(\\omega t + \\phi) + C_2  \\sin(\\omega t + \\phi)"
    }
  ],
  "difficultyLevels": {
    "veryEasy": false,
    "easy": false,
    "medium": true,
    "hard": false,
    "veryHard": false
  },
  "tags": []
}

###